-- ═══════════════════════════════════════════════════════════════
-- E.R.I.S.E. Bilingual (Arabic & English) Database Migration
-- Run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/ygougrhejaesbtifacdk/sql
-- ═══════════════════════════════════════════════════════════════

-- ──── 1. LEADERS TABLE: Bilingual Arabic Columns ────
ALTER TABLE leaders ADD COLUMN IF NOT EXISTS name_ar text;
ALTER TABLE leaders ADD COLUMN IF NOT EXISTS role_ar text;
ALTER TABLE leaders ADD COLUMN IF NOT EXISTS bio_ar text;
ALTER TABLE leaders ADD COLUMN IF NOT EXISTS specialty_ar text;

-- ──── 2. EVENTS TABLE: Bilingual Arabic Columns ────
ALTER TABLE events ADD COLUMN IF NOT EXISTS title_ar text;
ALTER TABLE events ADD COLUMN IF NOT EXISTS description_ar text;
ALTER TABLE events ADD COLUMN IF NOT EXISTS location_ar text;
ALTER TABLE events ADD COLUMN IF NOT EXISTS time_ar text;

-- ──── 3. ACHIEVEMENTS TABLE: Bilingual Arabic Columns ────
ALTER TABLE achievements ADD COLUMN IF NOT EXISTS title_ar text;
ALTER TABLE achievements ADD COLUMN IF NOT EXISTS description_ar text;
ALTER TABLE achievements ADD COLUMN IF NOT EXISTS category_ar text;

-- ──── 4. STAR MEMBERS TABLE: Bilingual Arabic Columns (if table exists) ────
CREATE TABLE IF NOT EXISTS star_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  name_ar text,
  image text,
  organization text,
  organization_ar text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE star_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read star_members" ON star_members FOR SELECT USING (true);
CREATE POLICY "Allow public all access star_members" ON star_members FOR ALL USING (true);

ALTER TABLE star_members ADD COLUMN IF NOT EXISTS name_ar text;
ALTER TABLE star_members ADD COLUMN IF NOT EXISTS organization_ar text;
