-- ═══════════════════════════════════════════════════════════════
-- E.R.I.S.E. Dynamic Event Registration System Schema
-- Run this script in your Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- ──── 1. UPDATE EVENTS TABLE FOR REGISTRATION CONTROLS ────
ALTER TABLE events ADD COLUMN IF NOT EXISTS registration_enabled boolean DEFAULT false;
ALTER TABLE events ADD COLUMN IF NOT EXISTS registration_type text DEFAULT 'individual'; -- 'individual' | 'team'
ALTER TABLE events ADD COLUMN IF NOT EXISTS registration_deadline timestamp with time zone;
ALTER TABLE events ADD COLUMN IF NOT EXISTS min_team_size integer DEFAULT 2;
ALTER TABLE events ADD COLUMN IF NOT EXISTS max_team_size integer DEFAULT 5;

-- ──── 2. CREATE EVENT REGISTRATIONS TABLE ────
CREATE TABLE IF NOT EXISTS event_registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint REFERENCES events(id) ON DELETE CASCADE,
  registration_type text NOT NULL DEFAULT 'individual',
  team_name text,
  institution text NOT NULL,
  study_year text NOT NULL,
  has_companion boolean NOT NULL DEFAULT false,
  companion_name text,
  companion_role text,
  status text NOT NULL DEFAULT 'pending', -- 'pending' | 'approved' | 'rejected'
  registered_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ──── 3. CREATE EVENT REGISTRATION MEMBERS TABLE ────
CREATE TABLE IF NOT EXISTS event_registration_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_id bigint REFERENCES event_registrations(id) ON DELETE CASCADE,
  is_leader boolean NOT NULL DEFAULT false,
  full_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ──── 4. ENABLE ROW LEVEL SECURITY ────
ALTER TABLE event_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_registration_members ENABLE ROW LEVEL SECURITY;

-- ──── 5. RLS POLICIES FOR PUBLIC ACCESS ────

-- Allow public read access to event registrations
CREATE POLICY "Allow public read event_registrations"
  ON event_registrations FOR SELECT USING (true);

-- Allow public insert to event registrations
CREATE POLICY "Allow public insert event_registrations"
  ON event_registrations FOR INSERT WITH CHECK (true);

-- Allow public update to event registrations (for admin status changes)
CREATE POLICY "Allow public update event_registrations"
  ON event_registrations FOR UPDATE USING (true);

-- Allow public delete to event registrations (for admin deletions)
CREATE POLICY "Allow public delete event_registrations"
  ON event_registrations FOR DELETE USING (true);

-- Allow public read access to members
CREATE POLICY "Allow public read event_registration_members"
  ON event_registration_members FOR SELECT USING (true);

-- Allow public insert to members
CREATE POLICY "Allow public insert event_registration_members"
  ON event_registration_members FOR INSERT WITH CHECK (true);

-- Allow public update to members
CREATE POLICY "Allow public update event_registration_members"
  ON event_registration_members FOR UPDATE USING (true);

-- Allow public delete to members
CREATE POLICY "Allow public delete event_registration_members"
  ON event_registration_members FOR DELETE USING (true);
