-- ═══════════════════════════════════════════════════════════════
-- E.R.I.S.E. Registration System Migration
-- Run this in the Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- 1. Registrations table — stores student sign-ups
CREATE TABLE IF NOT EXISTS registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  study_year integer NOT NULL CHECK (study_year BETWEEN 1 AND 5),
  specialization text,
  departments text[] NOT NULL DEFAULT '{}',
  registered_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Site settings table — key/value store for admin toggles
CREATE TABLE IF NOT EXISTS site_settings (
  key text PRIMARY KEY,
  value text NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default: registration is closed
INSERT INTO site_settings (key, value)
VALUES ('registration_open', 'false')
ON CONFLICT (key) DO NOTHING;

-- 3. Enable Row Level Security
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies

-- Site settings: anyone can read (frontend checks if registration is open)
CREATE POLICY "Allow public read access" ON site_settings FOR SELECT USING (true);
-- Site settings: full access for admin writes (toggle on/off)
CREATE POLICY "Allow public all access" ON site_settings FOR ALL USING (true);

-- Registrations: anyone can insert (public form submission)
CREATE POLICY "Allow public insert" ON registrations FOR INSERT WITH CHECK (true);
-- Registrations: anyone can read (admin dashboard fetches them)
CREATE POLICY "Allow public read access" ON registrations FOR SELECT USING (true);
-- Registrations: full access for admin delete/update
CREATE POLICY "Allow public all access" ON registrations FOR ALL USING (true);
