-- 1. Create admin_users table
CREATE TABLE IF NOT EXISTS admin_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  username text UNIQUE NOT NULL,
  password text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default admin user
INSERT INTO admin_users (username, password)
VALUES ('admin', 'admin123')
ON CONFLICT (username) DO NOTHING;


-- 2. Create leaders table
CREATE TABLE IF NOT EXISTS leaders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  role text NOT NULL,
  image text,
  socials jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create events table
CREATE TABLE IF NOT EXISTS events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  image text,
  date text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create achievements table
CREATE TABLE IF NOT EXISTS achievements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  image text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- Set up Row Level Security (RLS) policies
-- Enable RLS for all tables
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaders ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;

-- Allow public read access to all tables so the frontend can display them
CREATE POLICY "Allow public read access" ON admin_users FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON leaders FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON events FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON achievements FOR SELECT USING (true);

-- Allow all operations (insert, update, delete) for authenticated users or allow public for now
-- Since you use a custom admin_users table instead of Supabase Auth, you can temporarily allow public ALL access 
-- WARNING: In a real production app, you should lock this down!
CREATE POLICY "Allow public all access" ON leaders FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON events FOR ALL USING (true);
CREATE POLICY "Allow public all access" ON achievements FOR ALL USING (true);
