-- 1. Create star_members table
CREATE TABLE IF NOT EXISTS star_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  organization text NOT NULL,
  image text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for star_members
ALTER TABLE star_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON star_members FOR SELECT USING (true);
CREATE POLICY "Allow public all access" ON star_members FOR ALL USING (true);

-- 2. Setup Storage Bucket for Images (Requires Superuser/Postgres permissions or manual creation in Dashboard)
-- INSTRUCTIONS FOR DASHBOARD:
-- 1. Go to Supabase Dashboard -> Storage
-- 2. Click "New Bucket", name it "public_images"
-- 3. Make sure to toggle "Public bucket" ON!
-- 4. Save.

-- The following creates policies for the storage bucket (if it's created named 'public_images')
-- (Uncomment and run if you have permissions, otherwise just create it in the UI and set it to Public)

-- INSERT INTO storage.buckets (id, name, public) VALUES ('public_images', 'public_images', true) ON CONFLICT (id) DO NOTHING;
-- CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'public_images');
-- CREATE POLICY "Allow Uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'public_images');
-- CREATE POLICY "Allow Deletes" ON storage.objects FOR DELETE USING (bucket_id = 'public_images');
